#!/bin/bash

### $Id: install,v 1.1 2008-09-09 08:37:52 sfd Exp $

# install:  A script to create the working version of the Matrix
#           customization system.  It takes several flags and a
#           single target directory as arguments:
#      -l:  install locally (on this machine)
#      -r:  install remotely (on homer.u.washington.edu)
#      -m:  (with -l or -r) also install matrix-core
#      -c:  don't install, but create a copy of matrix-core locally
#
# Examples:
#      To install to www.delph-in.net/matrix:
#           ./install -r -m matrix/customize
#      To install to a local directory:
#           ./install -l -m [root directory of installation]
#      To install to a local directory without copying matrix-core:
#           ./install -l [root directory of installation]
#      To create a copy of matrix-core:
#           ./install -c [parent directory of matrix-core]


# parse command line
while [ "$1" = -l -o "$1" = -r -o "$1" = -c -o "$1" = -m ]
do
    if [ "$1" = -l ]
    then
        installlocal=true
    elif [ "$1" = -r ]
    then
        installremote=true
    elif [ "$1" = -c ]
    then
        copymatrix=true
    elif [ "$1" = -m ]
    then
        installmatrix=true
    fi
    shift
done

if [ $# != 1 -o ! \( "$installlocal" -o "$installremote" -o "$copymatrix" \) ]
then
    echo "Usage: $0 [-l|-r|-c] [-m] <directory name>"
    exit 1
fi


# create temporary staging directory
tempdir=/tmp/matrix.$$
mkdir $tempdir


# copy files to the temp directory
date -u > $tempdir/datestamp

if [ "$installremote" ]
then
    # Redirect the root directory to matrix.cgi
    echo "Redirect /uwcl/$1/index.html /uwcl/$1/matrix.cgi" >> \
        $tempdir/.htaccess

    # Don't allow directory browsing
    echo "IndexIgnore */*" >> \
        $tempdir/.htaccess

    # Don't allow access to the saved choices.  (Even with directory
    # browsing turned off, somebody could guess the filename.)
    mkdir $tempdir/saved-choices
    echo "Option -Indexes" >> \
        $tempdir/saved-choices/.htaccess
fi

mainfiles="matrix.cgi matrix.css matrix.js matrixdef customize.py deffile.py choices.py tdl.py utils.py validate.py util/*.py"
cp $mainfiles $tempdir

cp -R sample-choices $tempdir
rm -rf $tempdir/sample-choices/CVS $tempdir/sample-choices/.svn


# create matrix-core if necessary
if [ "$installmatrix" -o "$copymatrix" ]
then
    mkdir $tempdir/matrix-core
    mkdir $tempdir/matrix-core/lkb
    mkdir $tempdir/matrix-core/pet

    matrixfiles=`echo ../matrix-core/*.* ../matrix-core/README ../modules/basic_script | sed 's/[^ ]*my_language.tdl//g' | sed 's/[^ ]*Version.lsp//g' | sed 's/[^ ]*CVS//g' | sed 's/[^ ]*~//g'`

    cp $matrixfiles $tempdir/matrix-core

    lkbfiles=`echo ../matrix-core/lkb/* | sed 's/..\/lkb\/CVS//g'`
    cp $lkbfiles $tempdir/matrix-core/lkb

    petfiles=`echo ../matrix-core/pet/* | sed 's/..\/pet\/CVS//g'`
    cp $petfiles $tempdir/matrix-core/pet
fi


# copy the files to the appropriate target
if [ "$installlocal" -o "$copymatrix" ]
then
    cpcmd="cp -p -v -r"
    cptarg="$1"
elif [ "$installremote" ]
then
    cpcmd="scp -r"
    cptarg="uwcl@homer.u.washington.edu:public_html/$1"
fi

if [ "$copymatrix" ]
then
    $cpcmd $tempdir/matrix-core "$cptarg"
else
    shopt -s dotglob
    $cpcmd $tempdir/* "$cptarg"
    shopt -u dotglob
fi


# clean up
rm -rf $tempdir
