#!/bin/bash

if [ "$1" = -m ]
then
    copymatrix=true
    shift
fi

if [ $# != 1 ]
then
    echo "Usage: $0 [-m] <directory name>"
    exit 1
fi

scp `echo * | sed 's/[^ ]*~//g' | sed 's/[^ ]*pyc//g' | sed 's/#[^ ]*#//g' | sed 's/CVS//g' | sed 's/tohomer//g' | sed 's/tolocal//g' | sed 's/TODO//g'` uwcl@homer.u.washington.edu:public_html/$1

if [ $copymatrix ]
then
    scp -r ../*.tdl ../*.txt ../*.tab ../README ../lkb ../pet ../modules/basic_script uwcl@homer.u.washington.edu:public_html/$1/matrix-core
fi
