#!/bin/bash

#Note to Emily... for publishing this as www.delph-in.net/matrix:
#tolive -m matrix/customize

while [ "$1" = -m -o "$1" = -l ]
do
    if [ "$1" = -m ]
    then
        copymatrix=true
    elif [ "$1" = -l ]
    then
        copylocal=true
    fi
    shift
done

if [ $# != 1 ]
then
    echo "Usage: $0 [-m] [-l] <directory name>"
    exit 1
fi

if [ $copylocal ]
then
    cpcmd="cp -p -v"
    cptarg="$1"
else
    cpcmd="scp"
    cptarg="uwcl@homer.u.washington.edu:public_html/$1"
fi

mainfiles="matrix.cgi matrix.css matrixdef customize.py deffile.py choices.py tdl.py utils.py validate.py"

$cpcmd $mainfiles $cptarg

if [ $? = 1 ]
then
    echo ""
    echo "You must first go to ~/public_html on homer and create the target"
    echo "directory \"$1\", a subdirectory of \"$1\" called"
    echo "\"matrix-core\", and subdirectories of \"matrix-core\" called"
    echo "\"lkb\" and \"pet\"."
    exit
fi

if [ $copymatrix ]
then
    if [ $copylocal ]
    then
        mkdir -p "$cptarg/matrix-core"
        mkdir -p "$cptarg/matrix-core/lkb"
        mkdir -p "$cptarg/matrix-core/pet"
    fi
    matrixfiles=`echo ../*.* ../README ../modules/basic_script | sed 's/..\/my_language.tdl//g' | sed 's/..\/CVS//g'`
    $cpcmd $matrixfiles "$cptarg/matrix-core"

    lkbfiles=`echo ../lkb/* | sed 's/..\/lkb\/CVS//g'`
    $cpcmd $lkbfiles "$cptarg/matrix-core/lkb"

    petfiles=`echo ../pet/* | sed 's/..\/pet\/CVS//g'`
    $cpcmd $petfiles "$cptarg/matrix-core/pet"
fi
