# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test

on: [push]
  # pull_request:
  #   branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        python-version: '3.9'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install ace
        sudo apt-get update
        sudo apt-get install ace
    - name: List versions of things
      run: |
        python --version
        delphin --version
        which python 
        which delphin
        echo MADE IT HERE
        echo $PATH
        echo HEREEEE
        echo $GITHUB_PATH
        echo HERE2
        which ace
    - name: Test
      id: run-tests
      run: |
        python3 rtest.py wh-*
      continue-on-error: true 
    - name: Upload test logs as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: /home/runner/work/matrix/matrix/tests/regression/logs/*
    - name: Fail the job if the tests failed
      if: always()
      run: |
        if [ ${{ steps.run-tests.outcome }} != 'success' ]; then
            echo "Tests failed. Check logs for details."
            exit 1
          fi